openapi: 3.0.1

info:
  title: ClaimID - Claim IDentification/Embedding API
  description: >
    ClaimID extract claims from textual documents and generate 
    claim embeddings that can be used for identifying claims 
    on different types of content.
  version: "0.1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /claimid/embedding:
    get:
      summary: Get the claim embedding associated with a given sentence.
      operationId: claimid.api.claimid.embedding.get
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbeddingResponse"
      tags:
        - Claim Sentence Embedding

    post:
      summary: Get the claim embeddings associated with a list of sentences.
      operationId: claimid.api.claimid.embedding.post
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbeddingsListResponse"
      requestBody:
        description: A JSON object specifying the embedding query.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sentences:
                  description: A list of sentence that needs to be embedded.
                  type: array
                  items:
                    type: string
                callback_url:
                  description: A URL to be POSTed with the result of the job (must include api.coinform.eu domain for validation).
                  type: string
                  format: url
                  default: null
              required:
                - sentences
      tags:
        - Claim Sentence Embedding

  /claimid/identify:
    get:
      summary: Identifies if a given sentence is a claim.
      operationId: claimid.api.claimid.identify.get
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClaimResponse"
      parameters:
        - name: text
          in: query
          description: The sentence that needs to be checked.
          required: true
          schema:
            type: string
        - name: return_embeddings
          in: query
          description: If set, returns the sentence embedding.
          schema:
            type: boolean
            default: false
          allowEmptyValue: true
        - name: callback_url
          in: query
          description: A URL to be POSTed with the result of the job (must include api.coinform.eu domain for validation).
          schema:
            type: string
            format: url
      tags:
        - Claim Identification

    post:
      summary: Identify claims in a list of sentences.
      operationId: claimid.api.claimid.identify.post
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClaimsListResponse"
      requestBody:
        description: A JSON object specifying the embedding query.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sentences:
                  description: A list of sentence that needs to be embedded.
                  type: array
                  items:
                    type: string
                callback_url:
                  description: A URL to be POSTed with the result of the job (must include api.coinform.eu domain for validation).
                  type: string
                  format: url
                  default: null
                return_embeddings:
                  description: If set, returns each sentence embedding.
                  type: boolean
                  default: false
              required:
                - sentences
      tags:
        - Claim Identification

  /jobs/statuses:
    get:
      summary: Get the list of running and completed jobs.
      operationId: claimid.api.jobs.statuses.get_all
      parameters:
        - name: query_type
          in: query
          description: Filter the jobs by the type of query.
          required: false
          schema:
            type: string
            enum:
              - /claimid/identify
              - /claimid/embedding
        - name: status
          in: query
          description: Filter the jobs byt their status.
          required: false
          schema:
            type: string
            enum:
              - queued
              - finished
              - failed
              - started
              - deferred
              - scheduled
        - name: callback_url
          in: query
          description: Filter the jobs by callback_url.
          required: false
          schema:
            type: string
            format: url
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobStatusListResponse"
      tags:
        - Jobs

  /jobs/statuses/{job_id}:
    get:
      summary: Get the status of a given job.
      operationId: claimid.api.jobs.statuses.get
      parameters:
        - name: job_id
          description: The identifier of the job that needs to be retreived.
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobStatusResponse"
      tags:
        - Jobs

tags:
  - name: Claim Sentence Embedding
    description: Obtain embedding representation of sentences.
  - name: Claim Identification
    description: Identify if a sentence is a claim.
  #  - name: Claim Extraction
  #    description: Extract claims from text.
  - name: Jobs
    description: Obtain processing status for a query.

components:
  schemas:
    Response:
      type: object
      properties:
        status:
          description: Identifies if the query was successful.
          type: string
          enum: [success, fail, error]
        data:
          description: The response payload.
          nullable: true
        message:
          description: Explains the response status.
          type: string
          nullable: true
      required:
        - status

    Embedding:
      description: An embedding representation.
      type: array
      items:
        type: number

    EmbeddingResponse:
      description: A sentence claim embedding.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Embedding"

    EmbeddingsListResponse:
      description: A list of sentence claim embedding.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              description: An list of embedding representation.
              type: array
              items:
                $ref: "#/components/schemas/Embedding"

    Claim:
      description: An claim representation.
      type: object
      properties:
        label:
          description: Identifies if a sentence is a claim.
          type: string
          enum: [claim, not_claim]
        label_probs:
          type: object
          properties:
            claim:
              type: number
              minimum: 0
              maximum: 1
            not_claim:
              type: number
              minimum: 0
              maximum: 1
        embedding:
          description: If requested, the embedding representation of the claim.
          type: array
          items:
            type: number
          nullable: true

    ClaimResponse:
      description: Identifies if a sentence is a claim.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Claim"

    ClaimsListResponse:
      description: Identifies the claims in a list of sentences.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              description: A list identifying if sentences are claims.
              type: array
              items:
                $ref: "#/components/schemas/Claim"

    Extract:
      description: An extract representation.
      allOf:
        - $ref: "#/components/schemas/Claim"
        - type: object
          properties:
            sentence:
              description: The analysed sentence (may be tokenized).
              type: string
            offsets:
              description: The start and end positiojn of the sentence in the original text.
              type: array
              items:
                type: integer
                minimum: 0
              minItems: 2
              maxItems: 2
            index:
              description: The sentence index (position within the returned sentences list).
              type: integer
              minimum: 0

    ExtractsListResponse:
      description: Extract the claims in a text.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              description: A list identifying if sentences extracted.
              type: array
              items:
                $ref: "#/components/schemas/Extract"

    JobStatus:
      description: A job status.
      type: object
      properties:
        status:
          type: string
          enum:
            - queued
            - finished
            - failed
            - started
            - deferred
            - scheduled
        progress:
          description: The progress of the computation.
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        query_type:
          type: string
          enum:
            - /claimid/identify
            - /claimid/embedding
        result:
          $ref: "#/components/schemas/Response"
        callback_url:
          type: string
          format: url

    JobStatusResponse:
      description: A job status response.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/JobStatus"

    JobStatusListResponse:
      description: A list of Job statuses.
      allOf:
        - $ref: "#/components/schemas/Response"
        - type: object
          properties:
            data:
              description: An list of job statuses.
              type: array
              items:
                $ref: "#/components/schemas/JobStatus"
